package gui;

import controller.GuiController;
import javax.swing.JFrame;

/**
 *
 * @author Allan Neves Melquíades Silva
 */
public class FrameMenu extends javax.swing.JFrame {

    private GuiController guiController;

    public FrameMenu(GuiController guiController) {
        this.guiController = guiController;
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        mbarMenu = new javax.swing.JMenuBar();
        menuTurmas = new javax.swing.JMenu();
        mnuCadTurma = new javax.swing.JMenuItem();
        mnuListTurma = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mnuSair = new javax.swing.JMenuItem();
        menuAlunos = new javax.swing.JMenu();
        mnuCadAluno = new javax.swing.JMenuItem();
        mnuListAluno = new javax.swing.JMenuItem();
        menuDisciplinas = new javax.swing.JMenu();
        mnuCadDisc = new javax.swing.JMenuItem();
        mnuListDisciplina = new javax.swing.JMenuItem();
        menuAnos = new javax.swing.JMenu();
        mnuCadAno = new javax.swing.JMenuItem();
        menuGrade = new javax.swing.JMenu();
        mnuCadGrade = new javax.swing.JMenuItem();
        mnuListGrade = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 204, 204));
        setFont(new java.awt.Font("Malgun Gothic", 0, 12)); // NOI18N

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));
        jPanel1.setForeground(new java.awt.Color(255, 204, 204));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 601, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 319, Short.MAX_VALUE)
        );

        mbarMenu.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "MENU", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Malgun Gothic", 1, 12), new java.awt.Color(153, 0, 153))); // NOI18N
        mbarMenu.setToolTipText("");
        mbarMenu.setAutoscrolls(true);
        mbarMenu.setFont(new java.awt.Font("Malgun Gothic", 0, 12)); // NOI18N

        menuTurmas.setMnemonic('T');
        menuTurmas.setText("Turmas");
        menuTurmas.setFont(new java.awt.Font("Malgun Gothic", 0, 12)); // NOI18N

        mnuCadTurma.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.ALT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnuCadTurma.setFont(new java.awt.Font("Malgun Gothic", 0, 12)); // NOI18N
        mnuCadTurma.setText("Cadastrar Turma");
        mnuCadTurma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCadTurmaActionPerformed(evt);
            }
        });
        menuTurmas.add(mnuCadTurma);

        mnuListTurma.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnuListTurma.setFont(new java.awt.Font("Malgun Gothic", 0, 12)); // NOI18N
        mnuListTurma.setText("Listar Turmas");
        mnuListTurma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuListTurmaActionPerformed(evt);
            }
        });
        menuTurmas.add(mnuListTurma);
        menuTurmas.add(jSeparator1);

        mnuSair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, 0));
        mnuSair.setFont(new java.awt.Font("Malgun Gothic", 0, 12)); // NOI18N
        mnuSair.setText("Sair");
        mnuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSairActionPerformed(evt);
            }
        });
        menuTurmas.add(mnuSair);

        mbarMenu.add(menuTurmas);

        menuAlunos.setMnemonic('A');
        menuAlunos.setText("Alunos");
        menuAlunos.setFont(new java.awt.Font("Malgun Gothic", 0, 12)); // NOI18N

        mnuCadAluno.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.ALT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnuCadAluno.setFont(new java.awt.Font("Malgun Gothic", 0, 12)); // NOI18N
        mnuCadAluno.setText("Cadastrar Aluno");
        mnuCadAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCadAlunoActionPerformed(evt);
            }
        });
        menuAlunos.add(mnuCadAluno);

        mnuListAluno.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnuListAluno.setFont(new java.awt.Font("Malgun Gothic", 0, 12)); // NOI18N
        mnuListAluno.setText("Listar Alunos");
        mnuListAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuListAlunoActionPerformed(evt);
            }
        });
        menuAlunos.add(mnuListAluno);

        mbarMenu.add(menuAlunos);

        menuDisciplinas.setMnemonic('D');
        menuDisciplinas.setText("Disciplinas");
        menuDisciplinas.setFont(new java.awt.Font("Malgun Gothic", 0, 12)); // NOI18N

        mnuCadDisc.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.ALT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnuCadDisc.setFont(new java.awt.Font("Malgun Gothic", 0, 12)); // NOI18N
        mnuCadDisc.setText("Cadastrar Disciplina");
        mnuCadDisc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCadDiscActionPerformed(evt);
            }
        });
        menuDisciplinas.add(mnuCadDisc);

        mnuListDisciplina.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnuListDisciplina.setFont(new java.awt.Font("Malgun Gothic", 0, 12)); // NOI18N
        mnuListDisciplina.setText("Listar Disciplinas");
        mnuListDisciplina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuListDisciplinaActionPerformed(evt);
            }
        });
        menuDisciplinas.add(mnuListDisciplina);

        mbarMenu.add(menuDisciplinas);

        menuAnos.setText("Anos");
        menuAnos.setFont(new java.awt.Font("Malgun Gothic", 0, 12)); // NOI18N

        mnuCadAno.setFont(new java.awt.Font("Malgun Gothic", 0, 12)); // NOI18N
        mnuCadAno.setText("Cadastrar Ano");
        mnuCadAno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCadAnoActionPerformed(evt);
            }
        });
        menuAnos.add(mnuCadAno);

        mbarMenu.add(menuAnos);

        menuGrade.setText("Grade");
        menuGrade.setFont(new java.awt.Font("Malgun Gothic", 0, 12)); // NOI18N

        mnuCadGrade.setFont(new java.awt.Font("Malgun Gothic", 0, 12)); // NOI18N
        mnuCadGrade.setText("Cadastrar Grade");
        mnuCadGrade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCadGradeActionPerformed(evt);
            }
        });
        menuGrade.add(mnuCadGrade);

        mnuListGrade.setFont(new java.awt.Font("Malgun Gothic", 0, 12)); // NOI18N
        mnuListGrade.setText("Listar Grades");
        mnuListGrade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuListGradeActionPerformed(evt);
            }
        });
        menuGrade.add(mnuListGrade);

        mbarMenu.add(menuGrade);

        setJMenuBar(mbarMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuCadTurmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCadTurmaActionPerformed
        guiController.abrirCadastroTurma();
    }//GEN-LAST:event_mnuCadTurmaActionPerformed

    private void mnuListTurmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuListTurmaActionPerformed
        guiController.abrirListaTurma();
    }//GEN-LAST:event_mnuListTurmaActionPerformed

    private void mnuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSairActionPerformed
        dispose();
    }//GEN-LAST:event_mnuSairActionPerformed

    private void mnuCadDiscActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCadDiscActionPerformed
        guiController.abrirCadastroDisciplina();
    }//GEN-LAST:event_mnuCadDiscActionPerformed

    private void mnuListDisciplinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuListDisciplinaActionPerformed
        guiController.abrirListaDisciplina();
    }//GEN-LAST:event_mnuListDisciplinaActionPerformed

    private void mnuCadAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCadAlunoActionPerformed
        guiController.abrirCadastroAluno();
    }//GEN-LAST:event_mnuCadAlunoActionPerformed

    private void mnuListAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuListAlunoActionPerformed
        guiController.abrirListaAluno();
    }//GEN-LAST:event_mnuListAlunoActionPerformed

    private void mnuCadAnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCadAnoActionPerformed
        guiController.abrirCadastroAno();
    }//GEN-LAST:event_mnuCadAnoActionPerformed

    private void mnuCadGradeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCadGradeActionPerformed
        guiController.abrirCadastroGrade();
    }//GEN-LAST:event_mnuCadGradeActionPerformed

    private void mnuListGradeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuListGradeActionPerformed
        guiController.abrirListaGrade();
    }//GEN-LAST:event_mnuListGradeActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenuBar mbarMenu;
    private javax.swing.JMenu menuAlunos;
    private javax.swing.JMenu menuAnos;
    private javax.swing.JMenu menuDisciplinas;
    private javax.swing.JMenu menuGrade;
    private javax.swing.JMenu menuTurmas;
    private javax.swing.JMenuItem mnuCadAluno;
    private javax.swing.JMenuItem mnuCadAno;
    private javax.swing.JMenuItem mnuCadDisc;
    private javax.swing.JMenuItem mnuCadGrade;
    private javax.swing.JMenuItem mnuCadTurma;
    private javax.swing.JMenuItem mnuListAluno;
    private javax.swing.JMenuItem mnuListDisciplina;
    private javax.swing.JMenuItem mnuListGrade;
    private javax.swing.JMenuItem mnuListTurma;
    private javax.swing.JMenuItem mnuSair;
    // End of variables declaration//GEN-END:variables
}
