/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package gui.Listas;

import controller.GUIManager;
import domain.Aluno;
import domain.Turma;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.LinkedList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Allan Neves Melquíades Silva
 */
public class DialogListaAluno extends javax.swing.JDialog {

    private GUIManager guiManager;
    private Aluno alunSelec = null;

    public DialogListaAluno(java.awt.Frame parent, boolean modal, GUIManager guiManager) throws Exception {
        super(parent, modal);
        this.guiManager = guiManager;
        initComponents();
        List<Aluno> alunos = guiManager.getDbManager().listarAlunos();
        for (Aluno aluno : alunos) {
            ((DefaultTableModel) tblAlunos.getModel()).addRow(aluno.toArray());
        }

        try {
            List<Turma> turmas = this.guiManager.getDbManager().listarTurmas();
            List<String> descricoesTurmas = new LinkedList<>();
            for (Turma turma : turmas) {
                descricoesTurmas.add(turma.getDescricaoTurma());
            }
            ((DefaultComboBoxModel) cbbPesqAlunoTurma.getModel()).addAll(descricoesTurmas);

            if (!descricoesTurmas.isEmpty()) {
                cbbPesqAlunoTurma.setSelectedIndex(0);
            }
        } catch (Exception he) {
            JOptionPane.showMessageDialog(this, "Erro ao carregar turmas!\n");
        }

        tblAlunos.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent me) {
                // to detect doble click events
                JTable target = (JTable) me.getSource();
                int row = target.getSelectedRow(); // select a row
                if (me.getClickCount() == 2 && target.getSelectedRow() != -1) {
                    try {
                        alunSelec = guiManager.getDbManager().findByIdAluno((long) target.getValueAt(row, 0));
                        setVisible(false);
                    } catch (Exception ex) {
                        JOptionPane.showMessageDialog(target, "Erro ao selecionar aluno!\n");
                        ex.printStackTrace();
                    }
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlListaAlunos = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAlunos = new javax.swing.JTable();
        cbbPesqAlunoTurma = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        btnPesquisarAlunos = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtPesqAlunoNome = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 204, 204));

        pnlListaAlunos.setBackground(new java.awt.Color(255, 204, 204));
        pnlListaAlunos.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Lista de Alunos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Malgun Gothic", 1, 12))); // NOI18N
        pnlListaAlunos.setLayout(new java.awt.GridLayout(1, 0));

        tblAlunos.setBackground(new java.awt.Color(255, 204, 204));
        tblAlunos.setFont(new java.awt.Font("Malgun Gothic", 0, 12)); // NOI18N
        tblAlunos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nome", "Turma", "Data de Nascimento"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Long.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblAlunos);

        pnlListaAlunos.add(jScrollPane1);

        cbbPesqAlunoTurma.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<<TODAS>>" }));

        jLabel1.setText("Turma");

        btnPesquisarAlunos.setText("Pesquisar");
        btnPesquisarAlunos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarAlunosActionPerformed(evt);
            }
        });

        jLabel2.setText("Nome");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlListaAlunos, javax.swing.GroupLayout.DEFAULT_SIZE, 888, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(184, 184, 184)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cbbPesqAlunoTurma, 0, 351, Short.MAX_VALUE)
                    .addComponent(txtPesqAlunoNome))
                .addGap(49, 49, 49)
                .addComponent(btnPesquisarAlunos)
                .addContainerGap(184, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 24, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPesqAlunoNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbbPesqAlunoTurma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(btnPesquisarAlunos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(pnlListaAlunos, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPesquisarAlunosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarAlunosActionPerformed
        ((DefaultTableModel) tblAlunos.getModel()).setNumRows(0);

        String nome = txtPesqAlunoNome.getText();
        boolean nomeVazio = txtPesqAlunoNome.getText().isEmpty();
        String turma = (String) cbbPesqAlunoTurma.getSelectedItem();
        boolean turmaVazia = cbbPesqAlunoTurma.getSelectedIndex() < 1;

        try {
            if (nomeVazio && turmaVazia) {
                List<Aluno> alunos = guiManager.getDbManager().listarAlunos();
                for (Aluno aluno : alunos) {
                    ((DefaultTableModel) tblAlunos.getModel()).addRow(aluno.toArray());
                }
                return;
            }

            if (!nomeVazio && !turmaVazia) {
                List<Aluno> alunos = guiManager.getDbManager().pesquisarAlunoPorNomeETurma(nome.trim(), turma);
                for (Aluno aluno : alunos) {
                    ((DefaultTableModel) tblAlunos.getModel()).addRow(aluno.toArray());
                }
                return;
            }

            if (!turmaVazia) {
                List<Aluno> alunos = guiManager.getDbManager().pesquisarAlunoPorTurma(turma);
                for (Aluno aluno : alunos) {
                    ((DefaultTableModel) tblAlunos.getModel()).addRow(aluno.toArray());
                }
                return;
            }

            if (!nomeVazio) {
                List<Aluno> alunos = guiManager.getDbManager().pesquisarAlunoPorNome(nome.trim());
                for (Aluno aluno : alunos) {
                    ((DefaultTableModel) tblAlunos.getModel()).addRow(aluno.toArray());
                }
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Erro ao listar alunos!\n");
        }
    }//GEN-LAST:event_btnPesquisarAlunosActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPesquisarAlunos;
    private javax.swing.JComboBox<String> cbbPesqAlunoTurma;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnlListaAlunos;
    private javax.swing.JTable tblAlunos;
    private javax.swing.JTextField txtPesqAlunoNome;
    // End of variables declaration//GEN-END:variables

    public Aluno getAlunSelec() {
        return alunSelec;
    }
}
