package gui;

import controller.GUIManager;
import domain.Aluno;
import domain.Grade;
import java.util.List;
import javax.swing.JMenu;
import javax.swing.JOptionPane;

/**
 *
 * @author Allan Neves Melquíades Silva
 */
public class FrameMenu extends javax.swing.JFrame {

    private GUIManager guiManager;

    public FrameMenu(GUIManager guiManager) throws Exception {
        this.guiManager = guiManager;
        initComponents();
        if (!this.guiManager.getDbManager().listarDisciplinas().isEmpty() && !this.guiManager.getDbManager().listarAnos().isEmpty()) {
            menuGrade.setEnabled(true);
        }
        if (!this.guiManager.getDbManager().listarAnos().isEmpty()) {
            menuTurmas.setEnabled(true);
        }
        if (!this.guiManager.getDbManager().listarTurmas().isEmpty()) {
            menuAlunos.setEnabled(true);
        }
    }

    public JMenu getMenuAlunos() {
        return menuAlunos;
    }

    public JMenu getMenuTurmas() {
        return menuTurmas;
    }

    public JMenu getMenuGrades() {
        return menuGrade;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        mbarMenu = new javax.swing.JMenuBar();
        menuTurmas = new javax.swing.JMenu();
        mnuCadTurma = new javax.swing.JMenuItem();
        mnuListTurma = new javax.swing.JMenuItem();
        mnuAlunosPorTurma = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mnuSair = new javax.swing.JMenuItem();
        menuAlunos = new javax.swing.JMenu();
        mnuCadAluno = new javax.swing.JMenuItem();
        mnuListAluno = new javax.swing.JMenuItem();
        mnuAlunosAnivMes = new javax.swing.JMenuItem();
        menuDisciplinas = new javax.swing.JMenu();
        mnuCadDisc = new javax.swing.JMenuItem();
        mnuListDisciplina = new javax.swing.JMenuItem();
        menuAnos = new javax.swing.JMenu();
        mnuCadAno = new javax.swing.JMenuItem();
        menuGrade = new javax.swing.JMenu();
        mnuCadGrade = new javax.swing.JMenuItem();
        mnuListGrade = new javax.swing.JMenuItem();
        mnuPlanosEstudos = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 204, 204));
        setFont(new java.awt.Font("Malgun Gothic", 0, 12)); // NOI18N

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));
        jPanel1.setForeground(new java.awt.Color(255, 204, 204));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 601, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 319, Short.MAX_VALUE)
        );

        mbarMenu.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "MENU", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Malgun Gothic", 1, 12), new java.awt.Color(153, 0, 153))); // NOI18N
        mbarMenu.setToolTipText("");
        mbarMenu.setAutoscrolls(true);
        mbarMenu.setFont(new java.awt.Font("Malgun Gothic", 0, 12)); // NOI18N

        menuTurmas.setMnemonic('T');
        menuTurmas.setText("Turmas");
        menuTurmas.setEnabled(false);
        menuTurmas.setFont(new java.awt.Font("Malgun Gothic", 0, 12)); // NOI18N

        mnuCadTurma.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.ALT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnuCadTurma.setFont(new java.awt.Font("Malgun Gothic", 0, 12)); // NOI18N
        mnuCadTurma.setText("Cadastrar Turma");
        mnuCadTurma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCadTurmaActionPerformed(evt);
            }
        });
        menuTurmas.add(mnuCadTurma);

        mnuListTurma.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnuListTurma.setFont(new java.awt.Font("Malgun Gothic", 0, 12)); // NOI18N
        mnuListTurma.setText("Listar Turmas");
        mnuListTurma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuListTurmaActionPerformed(evt);
            }
        });
        menuTurmas.add(mnuListTurma);

        mnuAlunosPorTurma.setFont(new java.awt.Font("Malgun Gothic", 0, 12)); // NOI18N
        mnuAlunosPorTurma.setText("Alunos por Turma");
        mnuAlunosPorTurma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAlunosPorTurmaActionPerformed(evt);
            }
        });
        menuTurmas.add(mnuAlunosPorTurma);
        menuTurmas.add(jSeparator1);

        mnuSair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, 0));
        mnuSair.setFont(new java.awt.Font("Malgun Gothic", 0, 12)); // NOI18N
        mnuSair.setText("Sair");
        mnuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSairActionPerformed(evt);
            }
        });
        menuTurmas.add(mnuSair);

        mbarMenu.add(menuTurmas);

        menuAlunos.setMnemonic('A');
        menuAlunos.setText("Alunos");
        menuAlunos.setEnabled(false);
        menuAlunos.setFont(new java.awt.Font("Malgun Gothic", 0, 12)); // NOI18N

        mnuCadAluno.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.ALT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnuCadAluno.setFont(new java.awt.Font("Malgun Gothic", 0, 12)); // NOI18N
        mnuCadAluno.setText("Cadastrar Aluno");
        mnuCadAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCadAlunoActionPerformed(evt);
            }
        });
        menuAlunos.add(mnuCadAluno);

        mnuListAluno.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnuListAluno.setFont(new java.awt.Font("Malgun Gothic", 0, 12)); // NOI18N
        mnuListAluno.setText("Listar Alunos");
        mnuListAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuListAlunoActionPerformed(evt);
            }
        });
        menuAlunos.add(mnuListAluno);

        mnuAlunosAnivMes.setFont(new java.awt.Font("Malgun Gothic", 0, 12)); // NOI18N
        mnuAlunosAnivMes.setText("Aniversariantes do Mês");
        mnuAlunosAnivMes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAlunosAnivMesActionPerformed(evt);
            }
        });
        menuAlunos.add(mnuAlunosAnivMes);

        mbarMenu.add(menuAlunos);

        menuDisciplinas.setMnemonic('D');
        menuDisciplinas.setText("Disciplinas");
        menuDisciplinas.setFont(new java.awt.Font("Malgun Gothic", 0, 12)); // NOI18N

        mnuCadDisc.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.ALT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnuCadDisc.setFont(new java.awt.Font("Malgun Gothic", 0, 12)); // NOI18N
        mnuCadDisc.setText("Cadastrar Disciplina");
        mnuCadDisc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCadDiscActionPerformed(evt);
            }
        });
        menuDisciplinas.add(mnuCadDisc);

        mnuListDisciplina.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnuListDisciplina.setFont(new java.awt.Font("Malgun Gothic", 0, 12)); // NOI18N
        mnuListDisciplina.setText("Listar Disciplinas");
        mnuListDisciplina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuListDisciplinaActionPerformed(evt);
            }
        });
        menuDisciplinas.add(mnuListDisciplina);

        mbarMenu.add(menuDisciplinas);

        menuAnos.setText("Anos");
        menuAnos.setFont(new java.awt.Font("Malgun Gothic", 0, 12)); // NOI18N

        mnuCadAno.setFont(new java.awt.Font("Malgun Gothic", 0, 12)); // NOI18N
        mnuCadAno.setText("Cadastrar Ano");
        mnuCadAno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCadAnoActionPerformed(evt);
            }
        });
        menuAnos.add(mnuCadAno);

        mbarMenu.add(menuAnos);

        menuGrade.setText("Grade");
        menuGrade.setEnabled(false);
        menuGrade.setFont(new java.awt.Font("Malgun Gothic", 0, 12)); // NOI18N

        mnuCadGrade.setFont(new java.awt.Font("Malgun Gothic", 0, 12)); // NOI18N
        mnuCadGrade.setText("Cadastrar Grade");
        mnuCadGrade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCadGradeActionPerformed(evt);
            }
        });
        menuGrade.add(mnuCadGrade);

        mnuListGrade.setFont(new java.awt.Font("Malgun Gothic", 0, 12)); // NOI18N
        mnuListGrade.setText("Listar Grades");
        mnuListGrade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuListGradeActionPerformed(evt);
            }
        });
        menuGrade.add(mnuListGrade);

        mnuPlanosEstudos.setFont(new java.awt.Font("Malgun Gothic", 0, 12)); // NOI18N
        mnuPlanosEstudos.setText("Planos de Estudos");
        mnuPlanosEstudos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuPlanosEstudosActionPerformed(evt);
            }
        });
        menuGrade.add(mnuPlanosEstudos);

        mbarMenu.add(menuGrade);

        setJMenuBar(mbarMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuCadTurmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCadTurmaActionPerformed
        guiManager.abrirCadastroTurma();
    }//GEN-LAST:event_mnuCadTurmaActionPerformed

    private void mnuListTurmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuListTurmaActionPerformed
        guiManager.abrirListaTurma();
    }//GEN-LAST:event_mnuListTurmaActionPerformed

    private void mnuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSairActionPerformed
        dispose();
    }//GEN-LAST:event_mnuSairActionPerformed

    private void mnuCadDiscActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCadDiscActionPerformed
        guiManager.abrirCadastroDisciplina();
    }//GEN-LAST:event_mnuCadDiscActionPerformed

    private void mnuListDisciplinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuListDisciplinaActionPerformed
        guiManager.abrirListaDisciplina();
    }//GEN-LAST:event_mnuListDisciplinaActionPerformed

    private void mnuCadAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCadAlunoActionPerformed
        guiManager.abrirCadastroAluno();
    }//GEN-LAST:event_mnuCadAlunoActionPerformed

    private void mnuListAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuListAlunoActionPerformed
        guiManager.abrirListaAluno();
    }//GEN-LAST:event_mnuListAlunoActionPerformed

    private void mnuCadAnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCadAnoActionPerformed
        guiManager.abrirCadastroAno();
    }//GEN-LAST:event_mnuCadAnoActionPerformed

    private void mnuCadGradeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCadGradeActionPerformed
        guiManager.abrirCadastroGrade();
    }//GEN-LAST:event_mnuCadGradeActionPerformed

    private void mnuListGradeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuListGradeActionPerformed
        guiManager.abrirListaGrade();
    }//GEN-LAST:event_mnuListGradeActionPerformed

    private void mnuAlunosAnivMesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAlunosAnivMesActionPerformed
        try {
            List<Aluno> alunos = guiManager.getDbManager().listarAlunos();
            guiManager.getRelManager().getListRel(alunos, "relAlunosAnivMes.jasper");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Erro ao executar relatório!");
        }
    }//GEN-LAST:event_mnuAlunosAnivMesActionPerformed

    private void mnuAlunosPorTurmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAlunosPorTurmaActionPerformed
        try {
            List<Aluno> alunos = guiManager.getDbManager().listarAlunos();
            guiManager.getRelManager().getListRel(alunos, "relAlunosPorTurma.jasper");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Erro ao executar relatório!");
            ex.printStackTrace();
        }
    }//GEN-LAST:event_mnuAlunosPorTurmaActionPerformed

    private void mnuPlanosEstudosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuPlanosEstudosActionPerformed
        try {
            List<Grade> grades = guiManager.getDbManager().listarGrades();
            guiManager.getRelManager().getListRel(grades, "relPlanoEstudos.jasper");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Erro ao executar relatório!");
            ex.printStackTrace();
        }
    }//GEN-LAST:event_mnuPlanosEstudosActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenuBar mbarMenu;
    private javax.swing.JMenu menuAlunos;
    private javax.swing.JMenu menuAnos;
    private javax.swing.JMenu menuDisciplinas;
    private javax.swing.JMenu menuGrade;
    private javax.swing.JMenu menuTurmas;
    private javax.swing.JMenuItem mnuAlunosAnivMes;
    private javax.swing.JMenuItem mnuAlunosPorTurma;
    private javax.swing.JMenuItem mnuCadAluno;
    private javax.swing.JMenuItem mnuCadAno;
    private javax.swing.JMenuItem mnuCadDisc;
    private javax.swing.JMenuItem mnuCadGrade;
    private javax.swing.JMenuItem mnuCadTurma;
    private javax.swing.JMenuItem mnuListAluno;
    private javax.swing.JMenuItem mnuListDisciplina;
    private javax.swing.JMenuItem mnuListGrade;
    private javax.swing.JMenuItem mnuListTurma;
    private javax.swing.JMenuItem mnuPlanosEstudos;
    private javax.swing.JMenuItem mnuSair;
    // End of variables declaration//GEN-END:variables
}
